# Generated by Django 4.0.4 on 2022-05-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0002_deportista_fecha_de_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deportista',
            name='fecha_de_nacimiento',
            field=models.DateField(default=''),
        ),
    ]
