# Generated by Django 4.0.4 on 2022-05-24 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0004_inscripcion_horas_practicar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeportistaUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_ingreso', models.DateTimeField()),
                ('hora_salida', models.DateTimeField()),
                ('deportista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro.deportista')),
            ],
        ),
        migrations.CreateModel(
            name='PlanesDeportivos',
            fields=[
                ('uniqueId', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('max_horas', models.PositiveIntegerField(null=True)),
                ('min_horas', models.PositiveIntegerField(null=True)),
                ('valor_facturacion', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='deporte_id',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='deportista_id',
        ),
        migrations.DeleteModel(
            name='Deporte',
        ),
        migrations.DeleteModel(
            name='Inscripcion',
        ),
    ]
