# Generated by Django 4.0.4 on 2022-05-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='fecha_de_nacimiento',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='cita_medica',
            name='ubicacion',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
