# Generated by Django 4.0.4 on 2022-05-14 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0003_alter_paciente_fecha_de_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha_de_nacimiento',
            field=models.DateField(default=datetime.datetime(2022, 5, 14, 12, 16, 51, 768957)),
        ),
    ]
