# Generated by Django 4.0.4 on 2022-05-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='fecha_de_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
