# Generated by Django 4.0.4 on 2022-05-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0002_estudiante_fecha_de_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_de_nacimiento',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
