# Generated by Django 4.0.4 on 2022-05-14 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0006_alter_estudiante_fecha_de_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_de_nacimiento',
            field=models.DateField(default=datetime.datetime(2022, 5, 14, 12, 30, 22, 748467)),
        ),
    ]
