# Generated by Django 4.0.4 on 2022-05-14 17:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0007_alter_estudiante_fecha_de_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_de_nacimiento',
            field=models.DateField(default=datetime.datetime(2022, 5, 14, 17, 31, 8, 979421, tzinfo=utc)),
        ),
    ]
