# Generated by Django 4.0.4 on 2022-05-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0009_remove_estudiante_fecha_de_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='fecha_de_nacimiento',
            field=models.DateField(default=''),
        ),
    ]
